### ISSUE TITLE
Connection errors in API call to Automat using Cypher

### ISSUE THREAD

**Issue by dnwillia23** [RobokopU24/Issues#177]
In our notebook for exploring Scott's use case, we are sending 5000 Cypher queries via a for loop and sometimes getting a connection error (shown in the comment below).

Repo (main branch): https://github.com/RobokopU24/AOP-use-cases
Notebook: PPAR_LiverInjury_Automat_Debug.ipynb

The notebook sets up imports, search terms for the name resolver, directories for saving results, and getting the list of CURIES for each of the search terms.  A logger is also set up to record errors.  The error occurs in the code block under section header `### Running the full loop of ID lists`.  The nested for loops go through each list of IDs and submits a new Cypher query, each having a unique pair of IDs submitted.  A try-except block was set up to catch the occasional `ConnectionError` and attempt to reconnect.

Additionally, when sending queries via the Bolt protocol to `[robokopkg.renci.org](bolt://robokopkg.renci.org:7687)`, we are getting 127 pathways.  Here, when querying automat, we are only getting 10 pathways returned when using the same ID lists and queries.

**Comment by dnwillia23** [comment]
```
2023-07-27 10:29:59,776 ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Traceback (most recent call last):
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dnwilliams\AppData\Local\Temp\ipykernel_17008\278578291.py", line 32, in <module>
    results = requests.post(automat_cypher_submit_url,json=json_query, timeout=(40,200))
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\requests\adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2023-07-27 10:30:59,931 Starting new HTTPS connection (1): automat.renci.org:443
2023-07-27 10:30:59,935 HTTPSConnectionPool(host='automat.renci.org', port=443): Max retries exceeded with url: /robokopkg/cypher (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CD95332340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Traceback (most recent call last):
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001CD95332340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='automat.renci.org', port=443): Max retries exceeded with url: /robokopkg/cypher (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CD95332340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dnwilliams\AppData\Local\Temp\ipykernel_17008\278578291.py", line 32, in <module>
    results = requests.post(automat_cypher_submit_url,json=json_query, timeout=(40,200))
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\dnwilliams\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='automat.renci.org', port=443): Max retries exceeded with url: /robokopkg/cypher (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CD95332340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```
